### PR TITLE
Have more of the 2nd character sheet controlled by the configuration files

### PR DESCRIPTION
**Pull request by backwardsEric**
Added infrastructure to drive the resistance panel and object stat/sustain information in the character screen from the configuration files. ui_entry_renderer.txt configures types of formatting. The backend code is in list-ui-entry-renderers.h, ui-entry-renderers.h, and ui-entry-renderers.c. ui_entry.txt (with templates from ui_entry_base.txt) configures the links between object or player properties and those formatters. It also sets some details of the character screen (labels, category, order within category). The backend code is in ui-entry.h and ui-entry.c. ui-entry-init.h exposes the bits needed by init.c for initialization and cleanup. ui-player.c for the resistance panel and stat/sustain object information now largely just does placement and iteration over the elements. The data collection and computation is handled in ui-entry.c, and the formatting and display in ui-entry-renderers.c.

Part of the intent is that a "resistance grid for home" could also use this.

### CODE REVIEW

**Comment by NickMcConnell** [comment]
I'm still coming to grips with how all this works, and I thought asking a direct question I'm trying to answer might be the best next step.  For FAangband, I use percentage resistances, so I want a grid that looks like this in the character dump:

    Resistances              Abilities
     Acid:......+......  40% pFear:.............
     Elec:....+.+......  64% pBlnd:......?......
     Fire:......+......  40% pConf:.............
     Cold:......+......  40% pStun:......?......
     Pois:.............   0% HLife:.............
    Light:.............   0% Regen:.............
     Dark:.............   0%   ESP:......?......
    Sound:.............   0% S.Inv:.............
    Shard:......+......  40% FrAct:.............
    Nexus:......+......  40% Feath:......?......
    Nethr:.............   0% S.Dig:.............
    Chaos:.............   0% TrpIm:......?......
    Disen:.............   0% Bless:......?......
    
    Modifiers                Hindrances
    Stea.:.............   0  ImpHP:.............
    Sear.:.............   0  ImpSP:.............
    Infra:............+   0   Fear:......?......
    Tunn.:.............   0  Aggrv:.............
    Speed:..4..........   4  NoTel:......?......
    Blows:.............   0  DrExp:.............
    Shots:.............   0  Stick:......?......
    Might:.............   0  Fragl:......?......
    Light:.............   0
    D.Red:.............   0
    Moves:.............   0
and similar in the second 'C' screen but with all 4 panels horizontal.  How do I make your system do this?

**Comment by backwardsEric** [comment]
The 2 x 2 layout for the character dump and the 4 x 1 layout on the second character screen is still hardcoded in ui-player.c and isn't set from the configuration files - those are setting which attributes get mapped to the 4 panels.  Since FAAngband still uses the 2 x 2 for the dump and 4 x 1 for the character screen there wouldn't be any change necessary for that.  To get the modifiers to show up before the hindrances in the dump, you could change configure_char_sheet() in ui-player.c and put "modifiers" as the third category rather than the fourth (though that also changes its position in the second character sheet).

If you want a number rather than a +/-/. for something in the modifiers panel, you could (this uses speed as the example):

1. Set up a template in ui_entry_base.txt.  It would look something like

name:numeric_modifier_ui_0
renderer:char_screen1_numeric_renderer
combine:ADD
category:CHAR_SCREEN1
category:modifiers
flags:TIMED_AS_AUX

2. Change ui_entry.txt so that the modifier entries you want to show as digits use the template set up in (1).  So the speed entry would look like

name:speed_ui_compact_0
template:numeric_modifier_ui_0
label:Speed
priority:-4

3. Set up the renderer mentioned in (1) in ui_entry_renderer.txt.  It would look like

name:char_screen1_numeric_renderer
code:NUMERIC_RENDERER_WITH_COMBINED_AUX
colors:wwwBrbowwwBrbo
labelcolors:swBrww
symbols:?..*=*=
ndigit:1
sign:NO_SIGN

Those colors and label colors are the defaults.  How they're used is mentioned in the comment for NUMERIC_RENDERER_WITH_COMBINED_AUX in ui_entry_renderer.txt.  The symbols aren't the default since it looks like you want zero and no equipped item in the slot to be displayed as "." while the defaults would show those as "0".  Since no sign character is shown, positive and negative values are distinguished only by color.  The current character dumps from ui-player.c drop the color, so that could lead to some confusion.

For the column that gives the total resistance and total modifier, what I had implemented doesn't handle that.  One hack would be to modify display_resistance_panel() in ui-player.c to leave space for the column with the combined result when the loop index over the 4 categories is 0 or 2 (assuming you've put the "modifiers" as the third category).  Then draw the combined result directly from that loop. The vals array has the values for the permanent effect from each equipment slot and player for the current attribute.  The auxs array has the values for the timed effect so only the last element, for the player should potentially be nonzero.  If how to combine those values for the total is always the same (or at least the same for all attributes in the current category), there's enough information available to display_resistance_panel() to compute the total.  Otherwise, something would have to be changed since struct ui_entry is opaque and currently doesn't let you get much information about the property it represents.

A cleaner change would be to extend ui_entry_renderer_apply so it has the option of computing and displaying the total value.  Since it is already doing some form of total calculation to get the color of the label, that seems like a reasonable extension,  That would need additional fields in struct ui_entry_details (or additional parameters to ui_entry_renderer_apply) to specify whether a summary should be shown and its location.  Additional configuration information, probably most cleanly expressed as "use this other renderer to draw this renderer's total" would be needed in ui_entry_renderer.txt.  Another function in ui-entry-renderers.{h,c} also would be needed so ui-player.c could inquire about the width of the summary display.

The way that COMPACT_RESIST_RENDERER_WITH_AUX displays/combines resistance values probably isn't appropriate for FAAngband so something else would have to be set up for that.

**Comment by NickMcConnell** [comment]
Thanks, that really helps.  I had already worked out to swap "modifiers" and "hindrances", but after starting to try and understand the rest of it I realised that would be a whole lot simpler with a few pointers, which you've now given me.  I think now going through and doing the modifications for FA will be a really good way for me to get to know your system.

**Comment by backwardsEric** [comment]
I'll try to work up the extension to show a total value.

**Comment by NickMcConnell** [comment]
Thanks for all your work on this, and your specific help.  I ended up blundering my way through [getting percentage resists to actually display](https://github.com/NickMcConnell/FirstAgeAngband/commit/5da25a948db8b486d8c90d3ad75c518278dc111b) and [getting combined totals to display](https://github.com/NickMcConnell/FirstAgeAngband/commit/f0d85437251e8ab3672713d36001577236bf33ba), and finally [followed your instructions to use numbers in the modifier grid](https://github.com/NickMcConnell/FirstAgeAngband/commit/0718cb49e25d8c1ad80fadd2e825b53f8371d429).  Here's how it looks:
```
Resistances              Abilities
 Acid:.............   0% pFear:.............
 Elec:..+..........  70% pBlnd:.............
 Fire:..*.......... 100% pConf:.............
 Cold:.............   0% pStun:.............
 Pois:.............   0% HLife:.............
Light:.............   0% Regen:.............
 Dark:.............   0%   ESP:.............
Sound:.............   0% S.Inv:.............
Shard:..+..........  35% FrAct:.............
Nexus:..+..........  45% Feath:.............
Nethr:..-.......... -10% S.Dig:..+..........
Chaos:.............   0% TrpIm:.............
Disen:.............   0% Darkn:.............

Modifiers                Hindrances
Stea.:............. 0    ImpHP:.............
Sear.:............. 0    ImpSP:.............
Infra:............4 4     Fear:.............
Tunn.:1............ 1    Aggrv:.............
Speed:............. 0    NoTel:.............
Blows:............. 0    DrExp:.............
Shots:............. 0    Stick:.............
Might:............. 0    Fragl:.............
Light:............. 0
D.Red:............. 0
MMast:..4.......... 4
Moves:............. 0

```

**Pull request merged**
