### PR TITLE
Prevent monster death message from a missile from being garbled

### PR DESCRIPTION
**Pull request by backwardsEric**
Resolves https://github.com/angband/angband/issues/4988 .

### CODE REVIEW

**Comment by NickMcConnell** [comment]
How are the side effects happening, and are they going to be a worry in other situations?

**Comment by NickMcConnell** [comment]
Hm, I can kind of see, but it still makes me a bit uneasy.

**Comment by backwardsEric** [comment]
To clarify, it's expecting the internal buffer used by format()/vformat() to remain as it was before the call to notice_stuff().  The cases where the result from format() is explicitly assigned to something are easy to find.  Most seem okay:  the result is quickly used before something will have the chance to overwrite the buffer, though that assessment is relying on things like Term_putstr(), c_put_str(), msg(), and msgt() not having the side effect of calling format().  The ones that seemed riskier are:

1. The menu header for the menu to remove a curse; in curse_menu() at ui-curse.c:120
2. The "special" string in spell_effect_append_value_info(); that's depending on append_random_value_string() not using format() internally

I didn't try to track down where the result of format() is being used as a function argument or return value:  those might create other opportunities for mischief.

To be absolutely safe, the result of format() could always be immediately passed to string_make(), but then something has to deal with releasing the allocation.

**Comment by NickMcConnell** [comment]
Thanks, that all makes sense.  I have probably been too casual about using format() in the past.  I think we at least need to watch for this in future.

**Pull request merged**
