### PR TITLE
Add option to play again on death

### PR DESCRIPTION
**Pull request by sanedragon**

### CODE REVIEW

**Comment by sanedragon** [comment]
This isn't ready. I noticed after a few-thousand-turn character died that there were all sorts of weird bugs, and eventually the game crashed. The same issues don't seem to show up after a newer character dies.

**Comment by NickMcConnell** [comment]
Yes, not ready as is, but it should make it in with some adjustment

**Comment by NickMcConnell** [comment]
Which I'm now doing :)

**Comment by NickMcConnell** [comment]
This has now been pulled in, so I'm closing the PR

**Pull request closed without merging**
