### PR TITLE
Use C99 types for the fixed size integers

### PR DESCRIPTION
**Pull request by backwardsEric**
Resolves https://github.com/angband/angband/issues/3354 .

To hopefully make it easier for the forks to deal with, left the typedefs in h-basic.h (they can be omitted with the --enable-skip-old-int-typedefs option to configure or by setting the SKIP_ANGBAND_OLD_INT_TYPEDEFS preprocessor macro) and didn't change the names of the savefile routines, {rd,wr}_{byte,u32b,s32b,u16b,s16b}.

Did change occurrences of byte and u16b in the nds files but those changes haven't been tested at all.

### CODE REVIEW

**Comment by NickMcConnell** [comment]
Wow.  This is huge.

**Comment by backwardsEric** [comment]
That's presumably why the last stab at it (mentioned in #3354 ) wasn't committed.  Besides the impact on the nds front end, the visuals editing in ui-knowledge.c likely bears looking at since what was done there wasn't a strict byte->uint8_t conversion.

**Comment by NickMcConnell** [comment]
I will pull this in, but not immediately, as I want to think about the implications a bit.

**Comment by NickMcConnell** [comment]
So that was an attempted fix to some conflicts that came up subsequent to the PR; there's still an instance of byte in the combine-pack test, it's probably best if you pull that in.
I will pull this in soon, really...

**Comment by timschumi** [comment]
> Did change occurrences of byte and u16b in the nds files but those changes haven't been tested at all.

nds/3ds still works fine, most of those data types were largely just arbitrarily chosen anyways. The only data type that is really relevant is the pixel format, and that has been using `uint16_t`/`uint32_t` since the beginning.

**Comment by backwardsEric** [comment]
I redid the merge (wasn't sure how to pull what Nick did in to my local copy); looks to be the same as what Nick got.  I also applied the change to the combine_pack() test so it now compiles.

**Comment by NickMcConnell** [comment]
Yes, I tried to use the online editor to resolve conflicts, but then found the combine-pack() issue, and tried to fix that in command line...

**Comment by NickMcConnell** [comment]
I'm hoping to pull this in soon - maybe next weekend.

**Comment by NickMcConnell** [comment]
OK, what could possibly go wrong?

**Comment by NickMcConnell** [comment]
Brilliant, this was so smooth 😄

**Comment by draconisPW** [comment]
I don't understand this change. In h-basic.h, the Angband types were already mapped to C99 types by "typedef", so for example writing "s16b my_int" was identical to writing "int16_t my_int". Not defining SKIP_ANGBAND_OLD_INT_TYPEDEFS keeps the typedefs, but for what if all occurences of Angband types were replaced in the code...

**Comment by timschumi** [comment]
Commit (and Pull Request) messages are generally recommended for reading if you don't understand a change.

The main idea is to rely more on standard types, less on Angband-specific introductions. As an example, the Angband-specific types have caused [some confusion](https://github.com/angband/angband/commit/ee3e6bae3837c3eed2918591296bb97f0d6770fb) for me while porting the game to the NDS.

The flag for enabling or disabling is present because Angband isn't an isolated project. There are loads of forks with custom code (that frequently merge in updates from upstream), which may or may not rely on those custom types still being present.

**Comment by NickMcConnell** [comment]
We're just catching up with stuff that takkaria wanted to do 12 years ago

**Pull request merged**
