### PR TITLE
The alter command closes doors and open chests.

### PR DESCRIPTION
**Pull request by Cuboideb**
Nick, I know you want to release 4.2.1 very soon, so this is a small improvement (I think). I don't have any other pull requests pending.

### CODE REVIEW

**Comment by NickMcConnell** [comment]
I think that will also just open (not disarm) trapped chests, though - is that what we want?

**Comment by Cuboideb** [comment]
You are right! It should disarm the chest before open it! I will work on that.

**Comment by Cuboideb** [comment]
Done! It disarms the chest. Then, if you alter the chest again, it opens.

**Comment by NickMcConnell** [comment]
Nice 😄

**Pull request merged**
