### PR TITLE
More NDS port updates

### PR DESCRIPTION
**Pull request by timschumi**
## Major Changes:

* Run main-nds through a formatter ([skip this commit when looking at the diff](https://github.com/angband/angband/compare/226cafc1d408c125c902777e2b7b254b38759cbe...timschumi:nds))
* Remove graphics support
* Include the old 5x8 font
* Major refactoring
* Introduce support for the Nintendo 3DS
* New button and keyboard implementation

## A GIF (3DS)

<details>
<summary>Very great 3DS gameplay</summary>

</details>

### CODE REVIEW

**Comment by timschumi** [comment]
After some more testing, I don't think this is going to run very well, at least on the original hardware. I have downsized everything (most importantly the maximum number of monsters and the dungeon level size) to prevent the out-of-memory errors, and it still takes more than half an hour to generate a single dungeon level.

Regardless, if the changes here are sound, I might just turn it into a port for the 3DS (which means more screen space, more RAM and a faster CPU).

**Comment by NickMcConnell** [comment]
I think that's a good plan (and it's nice to see this!).  Do you need anything else at the moment?

**Comment by timschumi** [comment]
> Do you need anything else at the moment?

I don't think so, at least for now.

Since the original NDS pretty much appears to be a dead end performance-wise anyways, I don't think that we have to care about optimizing file loading/memory usage to accommodate for the old hardware at this point in time (contrary to what I said in the first message).

Also, I'll do some major refactoring before starting the 3DS port (NDS and 3DS can probably share a lot of code), so I don't know if doing a preliminary review already would be of much use (of course, unless you want the refactoring/3DS parts to be in a seperate PR).

**Comment by timschumi** [comment]
I'm now nearly finished with most of my planned changes, as well as with porting this to the 3DS. The only two remaining things that I still definitely want to look at is file saving (we apparently have a broken stat() function, so it doesn't create directories correctly) and wiring up the modifier keys to the Term input (should be quite easy, I just need to think about how I add that to the existing event implementation).

Anyways, the big changes are done as far as I can tell, so I don't think there is anything left that would keep us from starting to review this.

For convenience, I have updated the PR description with a rough overview of the major changes (although the commit history itself is probably more useful, since it's way more detailed and split into reviewable parts), the two TODOs that I still want to look at, and a GIF of current gameplay on the 3DS.

**Comment by NickMcConnell** [comment]
Excellent.  I'm not sure where to find reviewers - my knowledge of NDS programming is very outdated.  I guess posting something to the [Angband development forum](http://angband.oook.cz/forum/forumdisplay.php?f=10) is a possibility, or maybe you know of people in the NDS community who would be interested.

Failing a review, I guess we just pull it in when you think it's ready 😁

**Comment by davidk64fnq** [comment]
I just subscribed to Angband on github and the first email I get is about an NDS port which I own. Great I thought ... then I read this thread and found the bad news ... oh well :(

**Comment by timschumi** [comment]
>  I'm not sure where to find reviewers - my knowledge of NDS programming is very outdated.

I'm not necessarily concerned about the technical aspects that much (at least in a way where NDS-specific knowledge is integral), but rather about the coding style, structure, or Angband-specific changes (for example 196b6d67ed2dd44371dbb6a84a2be8383bcf70df, where I'm not sure if what I did is correct) and so on. After all, I've restructured and moved things around quite a bit.

> I guess posting something to the Angband development forum is a possibility.

Would that be good enough of a reason to revive the legendary "Angband on the Nintendo DS" thread? Although most people there probably weren't too savvy in regards to development (and the amount of people in there that additionally own a 3DS is probably quite small), I don't think that we would get much attention anywhere else...

> or maybe you know of people in the NDS community who would be interested.

I'm quite sure that the NDS homebrew scene is pretty much dead, and most of the developers likely moved on from the 3DS as well. Or at least every time I tried to ask things about NDS/3DS on various homebrew-related channels, interaction was... limited.

Regardless, I'll look for a few good places to post this (likely in places that are a bit more NDS-specific), maybe I can find a few people that would like to help.

**Comment by NickMcConnell** [comment]
Just let me know when this is ready to merge - I won't be running it personally, so I'll trust you 😄

**Comment by timschumi** [comment]
Thanks, will do once it's ready.

I just haven't had the time in the last few weeks to dig in and fix the few remaining issues, so I decided to convert this back into a draft until that is no longer the case.

**Comment by CodEsteban** [comment]
hey, are you these days? i can help and would like to see it released :)

**Comment by timschumi** [comment]
> hey, are you these days? i can help and would like to see it released :)

I'm still around, I just haven't continued this in a while. That said, I reinstalled the devkit yesterday and I'm hoping to get around to looking at (and hopefully fixing) a few of the remaining TODOs in the next few days/weeks if I get a bit of downtime between other obligations.

If you want to help, be it either reviewing the current changes (having at least a second pair of eyes would be awesome), looking into/fixing current TODOs, or thinking of and/or implementing other things that are still missing, I'd greatly appreciate it. In case you want to contribute code, feel free to post patches here or open a PR against my branch so that I can pull in your changes.

**Comment by CodEsteban** [comment]
> > hey, are you these days? i can help and would like to see it released :)
> 
> I'm still around, I just haven't continued this in a while. That said, I reinstalled the devkit yesterday and I'm hoping to get around to looking at (and hopefully fixing) a few of the remaining TODOs in the next few days/weeks if I get a bit of downtime between other obligations.
> 
> If you want to help, be it either reviewing the current changes (having at least a second pair of eyes would be awesome), looking into/fixing current TODOs, or thinking of and/or implementing other things that are still missing, I'd greatly appreciate it. In case you want to contribute code, feel free to post patches here or open a PR against my branch so that I can pull in your changes.

is there any way for contacting you? i have some questions, comunication is fundamental for reviving this port

**Comment by timschumi** [comment]
Both the saving/loading issues as well as the implementation of modifier keys should now be taken care of (the first one was actually partially caused by my flashcard being on a 2008 firmware, an update resolved that).

Since the old keyboard implementation relies on a prebuilt image of the framebuffer (something that has to be fetched from the old 2008 port and is hard to modify), I'd love to switch the NDS to the new keyboard implementation as well. However, since the 3x8 font is quite unreadable and we have more than enough space for rendering the keyboard using the 5x8 font, I'd prefer to use the latter one.

In the end, this means that we would need something to switch between those fonts on the fly, so I'm putting that into the TODO list next.

> is there any way for contacting you? i have some questions, comunication is fundamental for reviving this port

Other than Discord and maybe IRC, probably not. E-Mail would be an option as well, but I guess that's even less comfortable than commenting on a GitHub issue.

Unless there is a need for a quick real-time discussion, I'd probably prefer to keep the communication here anyways for others to read and maybe join in.

**Comment by NickMcConnell** [comment]
Angband does have a (little-used) presence on IRC at ``irc.libera.chat`` if you do want to use it.  There's a dev channel - ``#angband-dev`` - or I could set up an NDS specific one.

**Comment by timschumi** [comment]
> Angband does have a (little-used) presence on IRC at `irc.libera.chat` if you do want to use it. There's a dev channel - `#angband-dev` - or I could set up an NDS specific one.

Looking at the number of users that are in that channel, `-dev` would probably be just fine ;-)

I just have to remember to put my IRC client into autostart...

**Comment by asiekierka** [comment]
Have you considered using hardware-accelerated rendering for the 3DS? You can try to adapt the code from [here](https://github.com/OpenZoo/openzoo-cpp/tree/main/src/n3ds) - my 3DS port of ZZT, which also relies on text mode.

**Comment by asiekierka** [comment]
There's some questions brewing with regards to changes which would require input from upstream:

* Right now, Angband has ~3MB of constant memory usage on NDS (out of its 4MB). This requires users to reduce dungeon size to play the game. For users with Slot-2 expansion packs (like the DS Browser memory cartridge), this cold be alleviated, but at the cost of adding some helper methods which would allocate on Slot-2 on NDS and allocate as usual otherwise.
* For the 3DS port, it would be possible to add 3D depth support by utilizing more of the bits in the attribute int to pass depth information to the term renderer; however, of course, this implies more #ifdef magic.

What are your feelings on these?

**Pull request merged**
