### PR TITLE
Borgsource

### PR DESCRIPTION
**Pull request by agoodman00**
renamed and reorganized all the borg source files to, hopefully, be more supportable and easy to modify.

### CODE REVIEW

**Comment by agoodman00** [comment]
Did I somehow turn off "ALLOW_BORG"?  It seems to be getting "borg/borg-fight-attack.c:5092: warning: ISO C forbids an empty translation unit [-Wpedantic]" and that should only be "empty" if ALLOW_BORG is off.

**Comment by backwardsEric** [comment]
The builds using autoconf are the ones that fail.  To pick up the setting for ALLOW_BORG in those builds, the borg source files would have to include autoconf.h (the rest of the angband sources do that by including h-basic.h or angband.h).  Those include statements would have to be before the ifdef ALLOW_BORG tests.  That will have the side effect of likely resolving the empty compilation unit warnings when ALLOW_BORG is turned off.

**Comment by agoodman00** [comment]
ok all the borg headers include angband.h but inside ALLOW_BORG.  I will move it to outside and move the include of those headers to outside and that should do it.

**Comment by NickMcConnell** [comment]
I'm assuming this is good to go now

**Comment by agoodman00** [comment]
It is good from my perspective.  I don't know if you or @backwardsEric want to do any more review to make sure I didn't break anything while changing all the source files names.

**Comment by NickMcConnell** [comment]
Well, it tested OK - any issues can be fixed later

**Pull request merged**
