### PR TITLE
Avoid truncation of "-more-" prompt

### PR DESCRIPTION
**Pull request by backwardsEric**
Resolves agoodman's report here, https://angband.live/forums/forum/angband/vanilla/249005-message-ending-being-cut-off .  Avoids having to apply this workaround, https://github.com/angband/angband/pull/5991 , for the borg.

### CODE REVIEW

**Comment by agoodman00** [comment]
FYI I downloaded this change and tested it in the exact scenario I had and it works there.

**Comment by NickMcConnell** [comment]
Yeah, he's pretty good, isn't he 😄

**Comment by agoodman00** [comment]
You can decide if this is important... 
image

Note lack of space before -more-.  Previously there was always a space.  I can code around this in the borg easily enough.

**Comment by backwardsEric** [comment]
That should be addressed by https://github.com/angband/angband/pull/5998 .

**Pull request merged**
