### PR TITLE
Nuke the help files

### PR DESCRIPTION
**Pull request by takkaria**
Don't merge this yet - I have more work to do!

This removes most of the help from lib/help.

In progress:
- moving help for options out of option.txt and into list-options.h, then displaying it when pressing '?'
- editing symbol.txt & command.txt to be more useful

### CODE REVIEW

**Comment by NickMcConnell** [comment]
More of don't pull request, then

**Comment by takkaria** [comment]
Now it's a pull request!

**Comment by Archenoth** [comment]
Sorry to intrude in a closed PR, but I'm kinda curious. Why did the help system need to be removed..?

I'm not saying this should be undone or anything, but I was definitely more than a little confused when I went to look at the ingame help--confused enough I decided to look for the commit that did it, and just found this PR.

**Comment by takkaria** [comment]
I find it interesting that people have more affection/use for the in-game help than I thought they would - for me it was an awful reading format and it's obvious that there are much better ways to provide help and information.  Switching it over to online online help seemed to make sense from a usability perspective, mostly.

**Comment by Archenoth** [comment]
Ah, so it was just a usability tweak? I see..!

I'm not sure what kind of affection others have for it, but at least for me
personally, I just find it nice when everything is self contained. So even
without switching programs, and even if you didn't have an internet
connection at the moment, you could learn things that confused you; no
external resources were needed to learn everything you needed to play and
understand the game, and that was nice.

(That said, I do like the keybinding list too)

**Pull request merged**
