### PR TITLE
borg: work around to cut off '-more-'

### PR DESCRIPTION
**Pull request by agoodman00**

### CODE REVIEW

**Comment by agoodman00** [comment]
if you decide that https://angband.live/forums/forum/angband/vanilla/249005-message-ending-being-cut-off is a bug and check in a fix you can ignore this one.
I think the -more- could be restored with 
ui-input.c 
	/* Split message */
	while (n > w - 1) {
	
becomes
	/* Split message */
	while (n > w - 8) {	
	
but I am not sure...

**Comment by NickMcConnell** [comment]
OK, I'll think about this, and if I haven't done anything else soon I'll pull this in.

**Comment by backwardsEric** [comment]
Changing to "while (n > w - 8)" has the disadvantage that it will trigger an unnecessary "-more-" if n is greater than w - 8 and less than w - 1 and the message after that one is sent with msg_flag set to false.  To fix the underlying issue, I think the two places where ui-input.c uses msg_flush(message_column) will have to have additional logic to handle the case where message_column is greater than the terminal width minus 8.

**Comment by NickMcConnell** [comment]
Superseded by #5995

**Pull request closed without merging**
