### PR TITLE
Split effects

### PR DESCRIPTION
**Pull request by MarbleDice**
I mentioned a while ago I thought it would be a good idea to split the effect handlers out of the nearly **6000** line `effects.c` file. Here's what that might look like.

* Added two new files for effect handlers: `effect-handler-attack.c` (damage dealing effects and things closely related to them) and `effect-handler-general.c` (everything else). This takes line counts down to effects.c (**485**), effect-handler-general.c (**3427**), and effect-handler-attack.c (**2041**). Both effect handler files are still in the top 25 largest C files and further division would be possible but may not be necessary. I'm open to suggestions, for example there could be separate files for object-related handlers, detection, map-based handlers, etc.
* Added a new "private" header `effect-handler.h` for previously internal helper types and functions. This is used by all (and only) the effects and effect-handler C files, and includes automatic prototypes for every effect handler. Most of the static helper functions were able to remain static and localized within their appropriate effect-handler file, due to the lines of division, but it would be easy to promote them into the effect-handler header to make it easier to share across boundaries.
* The `effects.h` header remains the "public API" for the effects module, and `effects.c` still implements those functions.

Working on files of this size is easier for text editors, IDEs, and static analysis, so I do appreciate the smaller file size. I did my best to avoid making any changes to moved code, and I did resolve one merge conflict related to the `slot_type_is` method signature.

I tried to update all the various build files, but it's hard to know if I got all of them. Notably, I did not add any dependency information to `Makefile.inc`, so if that's not auto-generated I can go in and add it.

### CODE REVIEW

**Comment by NickMcConnell** [comment]
I can't see anything wrong with this, but I'm going to release 4.2.3 today (probably), and I'll actually leave this until after that.  There is definitely going to be a 4.2.4 (there's nothing of significance ready for 4.3 yet), and I want to get 4.2.3 out the door because of bugfixes and class improvements over 4.2.2.

**Comment by NickMcConnell** [comment]
I've pulled in some smaller things, too, so there will need to be some (small) changes to this one - sorry about that.

**Comment by MarbleDice** [comment]
All good, this should be pretty easy to keep up-to-date as long as no one goes crazy in effects.c.

**Comment by backwardsEric** [comment]
For the build files (excepting the dependencies in Makefile.inc which Nick has been updating once per release), it looks like you got everything.  The project files for Visual Studio also list the header files, so I'd add effect-handler.h in src/win/vs2019/Angband.vcxproj and src/win/vs2019/Angband.vcxproj.filters as well.  I've been trying to keep those insertions alphabetized so I locate where the file would go in the list, duplicate one of the adjacent listings, and replace the file name in the duplicate with the name of what's being added.

**Pull request merged**
