### PR TITLE
Borg 4x

### PR DESCRIPTION
**Pull request by agoodman00**
fixes for some of the recent borg bugs 
1) removes glyph from list of "can play with" spells so it is only cast when needed (caused issues to play)
2) fix crush_hole to not overflow by multiplying power... power tends to be a large number and multiplying it makes no sense unless somehow you think something makes you as strong as 100 borgs
3) fix crush_hole to track weight so heaving useless things get crushed first
4) fix to allow eating a larger variety of food when just "hungry" rather than starving.  This should help clean up food items in inventory some.

### CODE REVIEW

**Comment by NickMcConnell** [comment]
I think just adding commits onto this pull request is causing weirdness, so I'm closing it.  I've pulled in the new stuff via cherry-pick.  The best way to update the borg is to make yourself a clean local copy of the current angband/angband master branch, then make a new branch off that for any change you're making, then push that change branch and submit a (new) pull request for it.  Ask if this doesn't make sense 😄

**Comment by agoodman00** [comment]
So I think that means getting rid of the agoodman00/angband fork and using a branch off the main code?   Do I have that right?

**Comment by agoodman00** [comment]
@NickMcConnell 
ok, I did that (the clone/checkout above) and did a test change (removed an old comment) and tried to push it and got 
---
>git push
fatal: The current branch borg_4x has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin borg_4x

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.
---------
It isn't clear to me if I do that I am setting the upstream to "mainline" which is what I checked out from or a new branch named borg_4x... or if I need to have you create the branch for me on the server (I don't seem to be authorized to do it in the UI... probably wise, I would hate to hose things up).

**Comment by backwardsEric** [comment]
I'd check what 'git remote'  reports; that'll tell you what origin corresponds to.  As for the message you got with 'git push', I get that message (because I didn't follow the advice of configuring push.autoSetupRemote) when pushing a new branch to my repository on GitHub so when doing that I do 'git push --set-upstream name_of_remote_for_my_repository name_of_branch_to_push'.

**Comment by agoodman00** [comment]
I must be misunderstanding name_of's.  I tried 
git push --set-upstream https://github.com/angband/angband borg_4x
since I want a new branch (borg_4x) and the repository angband/angband but I get 

remote: Permission to angband/angband.git denied to agoodman00.
fatal: unable to access 'https://github.com/angband/angband/': The requested URL returned error: 403

maybe because I don't have permission to create a branch?  I could try reusing one of the defunct branches.  "borg" is out there and 10 years dead but I don't want to do that without you guys saying it is the right thing to do.

**Comment by backwardsEric** [comment]
Push the branch to your fork (if you're a member of the Angband organization you could push to https://github.com/angband/angband but I still wouldn't recommend doing that).  Then, when you want to create a pull request for Angband, you can use GitHub's web interface to create a pull request comparing that branch to Angband's master branch.

**Comment by agoodman00** [comment]
wait, I thought I was supposed to be getting rid of my fork because it was causing issues...  I think I need the exact commands that I should be running from the git command line to do this.  So far I have done 

git clone https://github.com/angband/angband
(to make myself a clean local copy of the current angband/angband master branch)
git checkout -b borg_4x
(to make a new branch... but this is a branch off angband/angband, not my fork)
*make changes locally and commit locally*

so... what now?  Have I already messed up?  If so, I haven't done much I can delete my local directories and be fine with it.  Should I be creating a new branch off agoodman00/angband?  Okay, never mind... I will stop guessing.  As I said, I think I need exact instructions.

**Comment by NickMcConnell** [comment]
That is all correct, and your local copy should now have two branches, master and borg_4x.
git branch
should show them.  You want to keep master as a copy of angband/angband:master at all times, and make new branches whenever you're doing something new - remember branches are cheap, when in doubt make a branch.
What you now want to do is make sure you have both angband/angband and agoodman00/angband as remotes.  Do 
git remote -v
to see what you have (I have angband/angband named 'official' and NickMcConnell/angband named 'origin', so I'll pretend those are your names for angband/angband and agoodman00/angband).  Now, here are the things you are likely to need to do:

git fetch official
git merge official master
will update your branch from the main repo

git checkout -b <name>
will make you a new branch off **your current branch** and switch to it (as you've done with your borg_4x)

git push origin <name>
will push your <name> branch to agoodman00/angband

This is now most of what you need; the general workflow for making changes is update master branch, make a new branch to do your changes, make the changes, push your branch with the changes to your origin repo, and then make a pull request on github to pull your branch into angband/angband.

There's lots of other stuff possible, but these are the important bits.

**Comment by agoodman00** [comment]
ok, I actually renamed my master "do_not_use"  on the server but I guess that doesn't "take" remote 
>git branch
* borg_4x
  master
>git remote -v
origin  https://github.com/agoodman00/angband (fetch)
origin  https://github.com/agoodman00/angband (push)

hmm, but I want the official one too ... so I did 
C:\Source\angband\GitHub\angband>git remote -v
origin  https://github.com/agoodman00/angband (fetch)
origin  https://github.com/agoodman00/angband (push)

>git remote add official https://github.com/angband/angband/

>git remote -v
official        https://github.com/angband/angband/ (fetch)
official        https://github.com/angband/angband/ (push)
origin  https://github.com/agoodman00/angband (fetch)
origin  https://github.com/agoodman00/angband (push)

>git checkout -b borg1
Switched to a new branch 'borg1'

> git push --set-upstream origin borg1
{did stuff} 

in another sandbox did 
>git fetch 
>git checkout borg1

I went to the web UI and it said something about do_not_use being behind so I told it to sync the branch and it said it would discard all my stuff... which is good, I think.  So, did that and I think it is now in sync with angband/angband master

so... I think I am good.  I am in a new branch off of agoodman00/angband named borg1.  I may play with renaming it at some point so I am always in the same named branch (so I can keep in sync with shelches who does testing for me) but for now I will just tell him to use borg1.

If I did something wrong, let me know.  I find the git stuff obscure.  Other version control software I used in past jobs were simpler but less robust.

**Comment by NickMcConnell** [comment]
That's all looking good from what I can see, and what you have done locally sounds correct.
How you manage your own branches is up to you.  @backwardsEric does a lot of pull requests, typically by making a new branch from master, pushing it, making a pull request, and then deleting that branch once it's been pulled in to official/master.  Just keeping a single change branch locally (your current borg1, say) and pushing that and doing a pull request from it when you're ready is fine, but you want to make sure you keep your master updated and keep your change branch updated from it.  I think it's probably best to do a new pull request when one has been pulled in, rather than adding commits to the old one -0 I'm not precisely sure of the github behaviour for the latter case.
My experience of git was it was confusing at first, but with use and liberal reading of documentation that improved, and I now find it quite intuitive.

**Pull request closed without merging**
