### PR TITLE
Support to CMake

### PR DESCRIPTION
**Pull request by Andres6936**
Currently, the support includes only Linux, the current frontend are X11, SDL and NCurses

### CODE REVIEW

**Comment by NickMcConnell** [comment]
Cool.  This is nice and simple, and should not be hard to maintain.  Are you planning to extend this to Windows?

**Comment by Andres6936** [comment]
Thank you very much @NickMcConnell , for the review.

> Are you planning to extend this to Windows?

Absolutely, in fact it is the goal, however the problem I have is that I don't have a Windows operating system installed and I can't perform the tests (I require help in this part).

In fact, this PR is part of an ambitious plan and as a first step CMake support is needed.

> This is nice and simple, and should not be hard to maintain

Believe me the last thing I want is a big CMakeLists.txt impossible to maintain or correct.

**Comment by Andres6936** [comment]
@NickMcConnell it's ok if I create a new directory named `cmake` to create CMake Macros and simplify the code even more?

**Comment by NickMcConnell** [comment]
Sure.  Think about where you want to put it - my guess is that in the top level directory is correct, but maybe inside src is a possibility too.

**Comment by Andres6936** [comment]
It has been impossible for me to add support to Windows with CMake due to the current limitations, the necessary configurations to give support to PDCurses in Windows are not given in a comfortable way (There are no scripts to find and link the library), a step to achieve this is to make a PDCurses fork and give support to CMake and then download it as a dependency with CPM.cmake (Simple, but in my case I don't have the necessary equipment for the tests) .

If we choose to use graphics in Windows, the files needed for the compilation escape my compression as I don't use Windows to see the process.

Support for Windows with CMake will be postponed until I can solve the testing problem.

**Pull request merged**
