### PR TITLE
Facilitate sharing randart sets by the seed value

### PR DESCRIPTION
**Pull request by backwardsEric**
To do that:

1. Include the seed in the character dump if randarts are used.
2. Extend the spoiler front end so it can accept a seed value as a way of specifying a randart set.  Processing the seed will have the side effect of generating the randart file and log.

### CODE REVIEW

**Comment by backwardsEric** [comment]
Estie, in a comment on the dump I posted to the ladder (to check whether including the seed would break dump submission), asked if the player could change the seed during character generation.  That's not done here.  Could do that as a simple get_string() prompt (either accept a randomly generated seed or edit it) as another stage in the birth process if randarts are enabled.

**Comment by NickMcConnell** [comment]
The simple way to achieve the same effect is to play with the randart option set to 'no', but place a copy of the randart file in the user directory named as 'artifact.txt'.  You do need to have access to the actual file, not just the seed, to do this, but if it's one of the player's previous randart sets it should be in their archive directory.

This system was implemented as a superior replacement for the old 'keep the same set of randarts' option.

**Comment by backwardsEric** [comment]
Yes, and I mentioned that option to Estie, in case that wasn't known, in the comments on that dump.  For the Windows and Mac front end, where it's easier to have multiple living characters at the same time, setting up lib/user/artifact.txt with a copy of the randart file can cause trouble:

- If there's a living character which was using the standard artifacts, loading that character with the randart set in place presumably breaks stuff.
- If one wants to start a new character with the standard artifact while one using that randart set is alive, one has to remember to deal with the customized artifact.txt if swapping between those characters.

The Windows and Mac front ends also can't use the spoiler front end so they wouldn't have access to the mechanism, already in this pull request, to turn a seed into a randart file, if all the player had was the seed.

So, as I see it, providing a direct way to specify the seed at birth has some utility.  I don't know if it's worth an extra prompt during the birth process.

**Comment by NickMcConnell** [comment]
I'll pull this in for now and we can think about further additions.

**Pull request merged**
