### PR TITLE
Add null and notnull test functions

### PR DESCRIPTION
**Pull request by NickMcConnell**
I believe this should now fix the relevant test warnings

### CODE REVIEW

**Comment by magnate** [comment]
http://pastebin.com/wZfK9R4K

Sorry not to be more help - no skill here.

**Comment by NickMcConnell** [comment]
OK, all updated with my latest guesses - if you could have another go when it's convenient, that would be wonderful

**Comment by NickMcConnell** [comment]
Now actually fixed by myshkin

**Comment by magnate** [comment]
Do we actually have two merge commits and two commits with the same name in this pullreq? Am I reading that right?

**Comment by magnate** [comment]
Merged by cherry-pick - well done chaps.

**Pull request closed without merging**
