### PR TITLE
Show speed multipliers in lore, if enabled

### PR DESCRIPTION
**Pull request by AlexMooney**
- [x] So far only shows the speed relative to normal speed.
- [x] I plan to also add a speed relative to the player.
- :disappointed: Unfortunately, I had to import `game-world` into `mon-lore` to get at `extract_energy`.

### CODE REVIEW

**Comment by NickMcConnell** [comment]
Including game-world.h is not a problem - I throw header file includes around like anything :)

**Comment by AlexMooney** [comment]
With 1.6x speed:
```
It is a smallish, slimy, icky, blobby creature.
This creature is normally found at depths of 50 feet (level 1), and moves
extremely erratically at 1.0x normal speed, which is 1.6x slower than you.
```
and
```
This evil creature is found at depths of 5000 feet (level 100), and moves at
3.8x normal speed, which is 2.3x faster than you.
```

With 1.0x speed:
```
It is a smallish, slimy, icky, blobby creature.
This creature is normally found at depths of 50 feet (level 1), and moves
extremely erratically at 1.0x normal speed, which is the same as you.
```
and
```
This evil creature is found at depths of 5000 feet (level 100), and moves at
3.8x normal speed, which is 3.8x faster than you.
```

**Comment by AlexMooney** [comment]
Made monsters that are faster than you round up to the scarier speed ratio.

At 1.6x speed, this monster moves 1.25x faster, which is rounded to 1.3x.
```
A dark elven figure, dressed all in black, hurling spells at you.
This evil creature is normally found at depths of 500 feet (level 10), and    
moves at 2.0x normal speed, which is 1.3x faster than you.
```

**Comment by NickMcConnell** [comment]
Done this by cherry-pick, closing

**Pull request closed without merging**
