### PR TITLE
Allow releasing of command spell under circumstances where 'r' would …

### PR DESCRIPTION
**Pull request by backwardsEric**
…run afoul of the checks for whether reading is possible.  Resolves https://github.com/angband/angband/issues/5056 .

### CODE REVIEW

**Comment by NickMcConnell** [comment]
Thanks, I was deciding which particular hack to do amend the command command hack...

**Comment by backwardsEric** [comment]
It looked to be a better fit to put it in player_can_read_prereq() rather than player_can_read(), though now player_can_read_prereq() is specific to the textui interface.  Perhaps it'd be better to have a separate prerequisite function for this.

Automatically canceling the command state for confusion or amnesia could make sense as well.

**Comment by NickMcConnell** [comment]
The other possibility I was thinking of was just to change the monster revert command to 'R' instead of 'r', which I think would just mean changing the command code (and help) in `do_cmd_mon_command()`.  I was still working out if there were any side-effects there.

**Comment by jl8e** [comment]
Players might want to rest while controlling a monster?

Is there a good reason that it has to overload a command at all? 

I'm looking at writing a patch to add an "end shapeshift" command, and was planning to use one of the free characters on the number row (!#%&( are unused, as is $, but it ends macros). Expanding the idea out to a general-purpose "end ongoing spell effect" command makes a lot of sense.

(I'd think that the shift-number characters would mess with the people who use the angband command set, but evidently not, since ^ and * are used already)

**Comment by NickMcConnell** [comment]
> Players might want to rest while controlling a monster?

They can't - they can only use the defined monster control commands.

> Is there a good reason that it has to overload a command at all?

The only reasons are to avoid adding another command, and to use a memorable key, but neither of those is very compelling.

> I'm looking at writing a patch to add an "end shapeshift" command, and was planning to use one of the free characters on the number row (!#%&( are unused, as is $, but it ends macros). Expanding the idea out to a general-purpose "end ongoing spell effect" command makes a lot of sense.
> 
> (I'd think that the shift-number characters would mess with the people who use the angband command set, but evidently not, since ^ and * are used already)

Yes, that's probably a good idea - I'd prefer one of #%&, as FAangband uses ! and $.

(Note that FAangband has Beornings which can change shape natively, and ! is their shapechange command; it also function as an end shapechange command for any character.  So for FA just overloading the ! would be an option, but I think having two separate commands which overlap somewhat in their effects is better).

In any case, I'm going to pull this in now as it actually fixes the bug 😄

**Pull request merged**
