### PR TITLE
Don't allow bloodlusted characters to attack from beyond the grave.  …

### PR DESCRIPTION
**Pull request by backwardsEric**
…Fixes a crash seen when reloading the savefile posted in https://github.com/angband/angband/issues/5599 .

### CODE REVIEW

**Comment by backwardsEric** [comment]
Likely want a more general solution than what I put in the pull request:

- Should bloodlust be triggering on commands that can't take energy (inscribing, changing options, checking knowledge, debugging commands, ...)?  If not, then one solution is to add a field to struct command_info to signal if the command can trigger bloodlust and test that field.
- If we don't filter by command, then bloodlust should not be triggering when in a store or in the birth process so could filter by the command context.  The crash I saw when loading the savefile from #5599 happened because bloodlust triggered on a command in the birth process.

**Comment by chowell2718** [comment]
Another comment on bloodlust- I've noticed that it can trigger whenever I give a command, so if I'm indecisive (maybe try to use magic to heal, but then quit out of the menu and try to quaff instead) I might randomly attack. It seems like better method would be to do the check for whether to get character control or lash out on the first command entered and then give control for the turn.

**Comment by backwardsEric** [comment]
The forced push only allows bloodlust to trigger on a command that could take energy (and is not a background command).  It doesn't try to implement chowell2718's suggestion of giving the player control after bloodlust triggers:  that would guarantee that the player could act at least every other turn.

**Comment by chowell2718** [comment]
To clarify, I don't mean that it should activate every other turn; instead, it should either trigger on a turn or not trigger  on that turn. It seems to have a chance to trigger whenever the player attempts to take an action that takes energy regardless of whether the player actually performs that action. For example, movement takes energy but accidentally moving into a wall does not. I tried moving into a wall multiple times and found that bloodlust would eventually trigger. Similarly, hitting quaff/cancel/quaff/cancel multiple times will eventually trigger it even though a potion was never selected. I think it should either activate on the first attempt to take an action on a turn or not activate on that turn.

**Comment by backwardsEric** [comment]
Ahh, that could be implemented (set flag at current point where bloodlust triggers, then defer firing it till after there's no chance to cancel the selected action).  My main concern is that it multiplies the number of places that  the code has to trigger bloodlust (for some actions, like reading a scroll of identify or reading a scroll of recharging, the last chance to cancel is buried in an effect handler so either have to rework that or add checks for triggering bloodlust to all effect handlers that a player could invoke).

**Comment by NickMcConnell** [comment]
Haven't read in detail, but the bloodlust direct interrupting of commands is a pretty horrible hack, if someone has a better solution they should go with it.

**Comment by NickMcConnell** [comment]
I'm not sure if this is ready, will take guidance

**Comment by backwardsEric** [comment]
As is, it doesn't address the hack in the command handling to implement bloodlust or chowell2718's request that canceling a command would avoid a reroll of the bloodlust check on the next command.  I think the latter could be implemented with the addition of a flag in the player state.  If there's spare padding bits for the player in the savefile, then that could be done without breaking savefile compatibility, otherwise resolving that request would have to wait till 4.3.

It does (at least in my hands) fix the crash on the death screen and avoids triggering bloodlust on commands that don't take energy.

**Comment by backwardsEric** [comment]
The latest forced push implements chowell2718's suggestion of skipping the bloodlust check after the player cancels a command that had successfully passed the bloodlust check.

**Comment by backwardsEric** [comment]
I believe it is.  It's still a hack, but the solution to that is probably to generalize how the command substitution is done.  For me, it is not clear how to do that until other cases where command substitution could be useful are identified (so far all I can think of is using command substitution as an alternative to the current implementation for confusion) and know how those other cases are the same or different than how bloodlust works.

**Pull request merged**
